### ISSUE TITLE
No "Structure & Coherence" score in the code implementation

### ISSUE THREAD

**Issue by VictorOtin** [WanzhengZhu/GRUEN#2]
Hi, thanks for sharing this amazing project. I really like it. 
The only problem that I find is that the fourth metric (Structure & Coherence) is not implemented in the code. Maybe you forget to add it?

It would be an incredible help if you could share it. :)

Thanks beforehand and have a nice weekend,

Victor

**Comment by WanzhengZhu** [comment]
please email zhuw0006@e.ntu.edu.sg for code
